//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataSqlSvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryDataDbContext : DbContext
    {
        public FactoryDataDbContext()
            : base("name=FactoryDataDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventTagRecord> EventTagRecords { get; set; }
        public virtual DbSet<Plc> Plcs { get; set; }
        public virtual DbSet<SubscriptionTagRecord> SubscriptionTagRecords { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagType> TagTypes { get; set; }
    }
}
