//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataSqlSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTagRecord
    {
        public int Id { get; set; }
        public int TagId { get; set; }
        public long Data { get; set; }
        public System.DateTime PlcTS { get; set; }
        public System.DateTime RecordTS { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
