//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataSqlSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plc()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IPAddress { get; set; }
        public bool DisableSubscriptions { get; set; }
        public int PollRateOverride { get; set; }
        public int ProcessorSlot { get; set; }
        public int Port { get; set; }
        public int EventPollRate { get; set; }
        public int SubscriptionPollRate { get; set; }
        public int TransactionPollRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
