//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataSqlSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag()
        {
            this.EventTagRecords = new HashSet<EventTagRecord>();
            this.SubscriptionTagRecords = new HashSet<SubscriptionTagRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TagTypeId { get; set; }
        public int PlcId { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTagRecord> EventTagRecords { get; set; }
        public virtual Plc Plc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTagRecord> SubscriptionTagRecords { get; set; }
        public virtual TagType TagType { get; set; }
    }
}
